function l(d){throw d;}var x=null;function A(){return function(){}}function E(d){return function(){return d}}function aa(){this.$a=1;this.Lb=4;this.Nb=0.5;this.ab=1E3;this.Ob=0.5;this.C=4;this.l=32}
function I(d,b,a,f,c){typeof c=="undefined"&&(c=d.$a<=0?Number.MAX_VALUE:(new Date).getTime()+d.$a*1E3);(b==x||a==x)&&l(Error("Null input. (diff_main)"));if(b==a)return b?[[0,b]]:[];typeof f=="undefined"&&(f=!0);var e=J(b,a),g=b.substring(0,e),b=b.substring(e),a=a.substring(e),e=K(b,a),h=b.substring(b.length-e),b=b.substring(0,b.length-e),a=a.substring(0,a.length-e),b=da(d,b,a,f,c);g&&b.unshift([0,g]);h&&b.push([0,h]);L(d,b);return b}
function da(d,b,a,f,c){if(!b)return[[1,a]];if(!a)return[[-1,b]];var e=b.length>a.length?b:a,g=b.length>a.length?a:b,h=e.indexOf(g);if(h!=-1)return d=[[1,e.substring(0,h)],[0,g],[1,e.substring(h+g.length)]],b.length>a.length&&(d[0][0]=d[2][0]=-1),d;if(g.length==1)return[[-1,b],[1,a]];if(e=ea(d,b,a))return a=e[1],g=e[3],b=e[4],e=I(d,e[0],e[2],f,c),d=I(d,a,g,f,c),e.concat([[0,b]],d);if(f&&b.length>100&&a.length>100){b=fa(b,a);f=b[0];a=b[1];b=b[2];f=ga(d,f,a,c);for(a=0;a<f.length;a++){e=f[a][1];g=[];
for(h=0;h<e.length;h++)g[h]=b[e.charCodeAt(h)];f[a][1]=g.join("")}ha(d,f);f.push([0,""]);g=e=a=0;for(h=b="";a<f.length;){switch(f[a][0]){case 1:g++;h+=f[a][1];break;case -1:e++;b+=f[a][1];break;case 0:if(e>=1&&g>=1){b=I(d,b,h,!1,c);f.splice(a-e-g,e+g);a=a-e-g;for(e=b.length-1;e>=0;e--)f.splice(a,0,b[e]);a+=b.length}e=g=0;h=b=""}a++}f.pop();d=f}else d=ga(d,b,a,c);return d}
function ga(d,b,a,f){for(var c=b.length,e=a.length,g=Math.ceil((c+e)/2),h=2*g,k=Array(h),i=Array(h),j=0;j<h;j++)k[j]=-1,i[j]=-1;k[g+1]=0;i[g+1]=0;for(var j=c-e,m=j%2!=0,n=0,p=0,r=0,w=0,t=0;t<g;t++){if((new Date).getTime()>f)break;for(var u=-t+n;u<=t-p;u+=2){var q=g+u,v;v=u==-t||u!=t&&k[q-1]<k[q+1]?k[q+1]:k[q-1]+1;for(var B=v-u;v<c&&B<e&&b.charAt(v)==a.charAt(B);)v++,B++;k[q]=v;if(v>c)p+=2;else if(B>e)n+=2;else if(m&&(q=g+j-u,q>=0&&q<h&&i[q]!=-1)){var y=c-i[q];if(v>=y)return ia(d,b,a,v,B,f)}}for(u=
-t+r;u<=t-w;u+=2){q=g+u;y=u==-t||u!=t&&i[q-1]<i[q+1]?i[q+1]:i[q-1]+1;for(v=y-u;y<c&&v<e&&b.charAt(c-y-1)==a.charAt(e-v-1);)y++,v++;i[q]=y;if(y>c)w+=2;else if(v>e)r+=2;else if(!m&&(q=g+j-u,q>=0&&q<h&&k[q]!=-1&&(v=k[q],B=g+v-q,y=c-y,v>=y)))return ia(d,b,a,v,B,f)}}return[[-1,b],[1,a]]}function ia(d,b,a,f,c,e){var g=b.substring(f),h=a.substring(c),b=I(d,b.substring(0,f),a.substring(0,c),!1,e),d=I(d,g,h,!1,e);return b.concat(d)}
function fa(d,b){function a(e){for(var a="",g=0,b=-1,d=f.length;b<e.length-1;){b=e.indexOf("\n",g);b==-1&&(b=e.length-1);var n=e.substring(g,b+1),g=b+1;(c.hasOwnProperty?c.hasOwnProperty(n):c[n]!==void 0)?a+=String.fromCharCode(c[n]):(a+=String.fromCharCode(d),c[n]=d,f[d++]=n)}return a}var f=[],c={};f[0]="";var e=a(d),g=a(b);return[e,g,f]}
function J(d,b){if(!d||!b||d.charAt(0)!=b.charAt(0))return 0;for(var a=0,f=Math.min(d.length,b.length),c=f,e=0;a<c;)d.substring(e,c)==b.substring(e,c)?e=a=c:f=c,c=Math.floor((f-a)/2+a);return c}function K(d,b){if(!d||!b||d.charAt(d.length-1)!=b.charAt(b.length-1))return 0;for(var a=0,f=Math.min(d.length,b.length),c=f,e=0;a<c;)d.substring(d.length-c,d.length-e)==b.substring(b.length-c,b.length-e)?e=a=c:f=c,c=Math.floor((f-a)/2+a);return c}
function ja(d,b){var a=d.length,f=b.length;if(a==0||f==0)return 0;a>f?d=d.substring(a-f):a<f&&(b=b.substring(0,a));a=Math.min(a,f);if(d==b)return a;for(var f=0,c=1;;){var e=b.indexOf(d.substring(a-c));if(e==-1)return f;c+=e;if(e==0||d.substring(a-c)==b.substring(0,c))f=c,c++}}
function ea(d,b,a){function f(e,a,c){for(var b=e.substring(c,c+Math.floor(e.length/4)),f=-1,d="",n,p,r,w;(f=a.indexOf(b,f+1))!=-1;){var t=J(e.substring(c),a.substring(f)),u=K(e.substring(0,c),a.substring(0,f));d.length<u+t&&(d=a.substring(f-u,f)+a.substring(f,f+t),n=e.substring(0,c-u),p=e.substring(c+t),r=a.substring(0,f-u),w=a.substring(f+t))}return d.length*2>=e.length?[n,p,r,w,d]:x}if(d.$a<=0)return x;var c=b.length>a.length?b:a,e=b.length>a.length?a:b;if(c.length<4||e.length*2<c.length)return x;
d=f(c,e,Math.ceil(c.length/4));c=f(c,e,Math.ceil(c.length/2));if(!d&&!c)return x;else d=c?d?d[4].length>c[4].length?d:c:c:d;b.length>a.length?(b=d[0],a=d[1],c=d[2],e=d[3]):(c=d[0],e=d[1],b=d[2],a=d[3]);return[b,a,c,e,d[4]]}
function ha(d,b){for(var a=!1,f=[],c=0,e=x,g=0,h=0,k=0,i=0,j=0;g<b.length;)b[g][0]==0?(f[c++]=g,h=i,k=j,j=i=0,e=b[g][1]):(b[g][0]==1?i+=b[g][1].length:j+=b[g][1].length,e!==x&&e.length<=Math.max(h,k)&&e.length<=Math.max(i,j)&&(b.splice(f[c-1],0,[-1,e]),b[f[c-1]+1][0]=1,c--,c--,g=c>0?f[c-1]:-1,j=i=k=h=0,e=x,a=!0)),g++;a&&L(d,b);ka(b);for(g=1;g<b.length;){if(b[g-1][0]==-1&&b[g][0]==1){a=b[g-1][1];f=b[g][1];c=ja(a,f);e=ja(f,a);if(c>=e){if(c>=a.length/2||c>=f.length/2)b.splice(g,0,[0,f.substring(0,c)]),
b[g-1][1]=a.substring(0,a.length-c),b[g+1][1]=f.substring(c),g++}else if(e>=a.length/2||e>=f.length/2)b.splice(g,0,[0,a.substring(0,e)]),b[g-1]=[1,f.substring(0,f.length-e)],b[g+1]=[-1,a.substring(e)],g++;g++}g++}}
function ka(d){function b(e,a){if(!e||!a)return 6;var c=e.charAt(e.length-1),g=a.charAt(0),b=c.match(la),h=g.match(la),f=b&&c.match(ma),d=h&&g.match(ma),c=f&&c.match(na),g=d&&g.match(na),k=c&&e.match(oa),i=g&&a.match(pa);if(k||i)return 5;else if(c||g)return 4;else if(b&&!f&&d)return 3;else if(f||d)return 2;else if(b||h)return 1;return 0}for(var a=1;a<d.length-1;){if(d[a-1][0]==0&&d[a+1][0]==0){var f=d[a-1][1],c=d[a][1],e=d[a+1][1],g=K(f,c);if(g)var h=c.substring(c.length-g),f=f.substring(0,f.length-
g),c=h+c.substring(0,c.length-g),e=h+e;for(var g=f,h=c,k=e,i=b(f,c)+b(c,e);c.charAt(0)===e.charAt(0);){f+=c.charAt(0);var c=c.substring(1)+e.charAt(0),e=e.substring(1),j=b(f,c)+b(c,e);j>=i&&(i=j,g=f,h=c,k=e)}d[a-1][1]!=g&&(g?d[a-1][1]=g:(d.splice(a-1,1),a--),d[a][1]=h,k?d[a+1][1]=k:(d.splice(a+1,1),a--))}a++}}var la=/[^a-zA-Z0-9]/,ma=/\s/,na=/[\r\n]/,oa=/\n\r?\n$/,pa=/^\r?\n\r?\n/;
function qa(d,b){for(var a=!1,f=[],c=0,e="",g=0,h=!1,k=!1,i=!1,j=!1;g<b.length;){if(b[g][0]==0)b[g][1].length<d.Lb&&(i||j)?(f[c++]=g,h=i,k=j,e=b[g][1]):(c=0,e=""),i=j=!1;else if(b[g][0]==-1?j=!0:i=!0,e&&(h&&k&&i&&j||e.length<d.Lb/2&&h+k+i+j==3))b.splice(f[c-1],0,[-1,e]),b[f[c-1]+1][0]=1,c--,e="",h&&k?(i=j=!0,c=0):(c--,g=c>0?f[c-1]:-1,i=j=!1),a=!0;g++}a&&L(d,b)}
function L(d,b){b.push([0,""]);for(var a=0,f=0,c=0,e="",g="",h;a<b.length;)switch(b[a][0]){case 1:c++;g+=b[a][1];a++;break;case -1:f++;e+=b[a][1];a++;break;case 0:f+c>1?(f!==0&&c!==0&&(h=J(g,e),h!==0&&(a-f-c>0&&b[a-f-c-1][0]==0?b[a-f-c-1][1]+=g.substring(0,h):(b.splice(0,0,[0,g.substring(0,h)]),a++),g=g.substring(h),e=e.substring(h)),h=K(g,e),h!==0&&(b[a][1]=g.substring(g.length-h)+b[a][1],g=g.substring(0,g.length-h),e=e.substring(0,e.length-h))),f===0?b.splice(a-f-c,f+c,[1,g]):c===0?b.splice(a-f-
c,f+c,[-1,e]):b.splice(a-f-c,f+c,[-1,e],[1,g]),a=a-f-c+(f?1:0)+(c?1:0)+1):a!==0&&b[a-1][0]==0?(b[a-1][1]+=b[a][1],b.splice(a,1)):a++,f=c=0,g=e=""}b[b.length-1][1]===""&&b.pop();f=!1;for(a=1;a<b.length-1;)b[a-1][0]==0&&b[a+1][0]==0&&(b[a][1].substring(b[a][1].length-b[a-1][1].length)==b[a-1][1]?(b[a][1]=b[a-1][1]+b[a][1].substring(0,b[a][1].length-b[a-1][1].length),b[a+1][1]=b[a-1][1]+b[a+1][1],b.splice(a-1,1),f=!0):b[a][1].substring(0,b[a+1][1].length)==b[a+1][1]&&(b[a-1][1]+=b[a+1][1],b[a][1]=b[a][1].substring(b[a+
1][1].length)+b[a+1][1],b.splice(a+1,1),f=!0)),a++;f&&L(d,b)}function M(d,b){var a=0,f=0,c=0,e=0,g;for(g=0;g<d.length;g++){d[g][0]!==1&&(a+=d[g][1].length);d[g][0]!==-1&&(f+=d[g][1].length);if(a>b)break;c=a;e=f}return d.length!=g&&d[g][0]===-1?e:e+(b-c)}function O(d){for(var b=[],a=0;a<d.length;a++)d[a][0]!==1&&(b[a]=d[a][1]);return b.join("")}function ra(d){for(var b=[],a=0;a<d.length;a++)d[a][0]!==-1&&(b[a]=d[a][1]);return b.join("")}
function sa(d){for(var b=0,a=0,f=0,c=0;c<d.length;c++){var e=d[c][1];switch(d[c][0]){case 1:a+=e.length;break;case -1:f+=e.length;break;case 0:b+=Math.max(a,f),f=a=0}}b+=Math.max(a,f);return b}function wa(d){for(var b=[],a=0;a<d.length;a++)switch(d[a][0]){case 1:b[a]="+"+encodeURI(d[a][1]);break;case -1:b[a]="-"+d[a][1].length;break;case 0:b[a]="="+d[a][1].length}return b.join("\t").replace(/%20/g," ")}
function P(d,b){for(var a=[],f=0,c=0,e=b.split(/\t/g),g=0;g<e.length;g++){var h=e[g].substring(1);switch(e[g].charAt(0)){case "+":try{a[f++]=[1,decodeURI(h)]}catch(k){l(Error("Illegal escape in diff_fromDelta: "+h))}break;case "-":case "=":var i=parseInt(h,10);(isNaN(i)||i<0)&&l(Error("Invalid number in diff_fromDelta: "+h));h=d.substring(c,c+=i);e[g].charAt(0)=="="?a[f++]=[0,h]:a[f++]=[-1,h];break;default:e[g]&&l(Error("Invalid diff operation in diff_fromDelta: "+e[g]))}}c!=d.length&&l(Error("Delta length ("+
c+") does not equal source text length ("+d.length+")."));return a}function R(d,b,a,f){(b==x||a==x||f==x)&&l(Error("Null input. (match_main)"));f=Math.max(0,Math.min(f,b.length));return b==a?0:b.length?b.substring(f,f+a.length)==a?f:xa(d,b,a,f):-1}
function xa(d,b,a,f){function c(e,c){var b=e/a.length,h=Math.abs(f-c);return!g.ab?h?1:b:b+h/g.ab}a.length>d.l&&l(Error("Pattern too long for this browser."));var e=ya(a),g=d,d=d.Nb,h=b.indexOf(a,f);h!=-1&&(d=Math.min(c(0,h),d),h=b.lastIndexOf(a,f+a.length),h!=-1&&(d=Math.min(c(0,h),d)));for(var k=1<<a.length-1,h=-1,i,j,m=a.length+b.length,n,p=0;p<a.length;p++){i=0;for(j=m;i<j;)c(p,f+j)<=d?i=j:m=j,j=Math.floor((m-i)/2+i);m=j;i=Math.max(1,f-j+1);var r=Math.min(f+j,b.length)+a.length;j=Array(r+2);for(j[r+
1]=(1<<p)-1;r>=i;r--){var w=e[b.charAt(r-1)];j[r]=p===0?(j[r+1]<<1|1)&w:(j[r+1]<<1|1)&w|(n[r+1]|n[r])<<1|1|n[r+1];if(j[r]&k&&(w=c(p,r-1),w<=d))if(d=w,h=r-1,h>f)i=Math.max(1,2*f-h);else break}if(c(p+1,f)>d)break;n=j}return h}function ya(d){for(var b={},a=0;a<d.length;a++)b[d.charAt(a)]=0;for(a=0;a<d.length;a++)b[d.charAt(a)]|=1<<d.length-a-1;return b}
function za(d,b,a){if(a.length!=0){for(var f=a.substring(b.i,b.i+b.g),c=0;a.indexOf(f)!=a.lastIndexOf(f)&&f.length<d.l-d.C-d.C;)c+=d.C,f=a.substring(b.i-c,b.i+b.g+c);c+=d.C;(d=a.substring(b.i-c,b.i))&&b.b.unshift([0,d]);(a=a.substring(b.i+b.g,b.i+b.g+c))&&b.b.push([0,a]);b.A-=d.length;b.i-=d.length;b.g+=d.length+a.length;b.k+=d.length+a.length}}
function S(d,b,a){var f,c;typeof b=="string"&&typeof a=="string"?(f=b,c=I(d,f,a,!0),c.length>2&&(ha(d,c),qa(d,c))):b&&typeof b=="object"&&typeof a=="undefined"?(c=b,f=O(c)):typeof b=="string"&&a&&typeof a=="object"?(f=b,c=a):l(Error("Unknown call format to patch_make."));if(c.length===0)return[];for(var b=[],a=new T,e=0,g=0,h=0,k=f,i=0;i<c.length;i++){var j=c[i][0],m=c[i][1];if(!e&&j!==0)a.A=g,a.i=h;switch(j){case 1:a.b[e++]=c[i];a.k+=m.length;f=f.substring(0,h)+m+f.substring(h);break;case -1:a.g+=
m.length;a.b[e++]=c[i];f=f.substring(0,h)+f.substring(h+m.length);break;case 0:m.length<=2*d.C&&e&&c.length!=i+1?(a.b[e++]=c[i],a.g+=m.length,a.k+=m.length):m.length>=2*d.C&&e&&(za(d,a,k),b.push(a),a=new T,e=0,k=f,g=h)}j!==1&&(g+=m.length);j!==-1&&(h+=m.length)}e&&(za(d,a,k),b.push(a));return b}function Aa(d){for(var b=[],a=0;a<d.length;a++){var f=d[a],c=new T;c.b=[];for(var e=0;e<f.b.length;e++)c.b[e]=f.b[e].slice();c.A=f.A;c.i=f.i;c.g=f.g;c.k=f.k;b[a]=c}return b}
function U(d,b,a){if(b.length==0)return[a,[]];var b=Aa(b),f=Ba(d,b),a=f+a+f;Ca(d,b);for(var c=0,e=[],g=0;g<b.length;g++){var h=b[g].i+c,k=O(b[g].b),i,j=-1;if(k.length>d.l){if(i=R(d,a,k.substring(0,d.l),h),i!=-1&&(j=R(d,a,k.substring(k.length-d.l),h+k.length-d.l),j==-1||i>=j))i=-1}else i=R(d,a,k,h);if(i==-1)e[g]=!1,c-=b[g].k-b[g].g;else if(e[g]=!0,c=i-h,h=j==-1?a.substring(i,i+k.length):a.substring(i,j+d.l),k==h)a=a.substring(0,i)+ra(b[g].b)+a.substring(i+k.length);else if(h=I(d,k,h,!1),k.length>d.l&&
sa(h)/k.length>d.Ob)e[g]=!1;else{ka(h);for(var k=0,m,j=0;j<b[g].b.length;j++){var n=b[g].b[j];n[0]!==0&&(m=M(h,k));n[0]===1?a=a.substring(0,i+m)+n[1]+a.substring(i+m):n[0]===-1&&(a=a.substring(0,i+m)+a.substring(i+M(h,k+n[1].length)));n[0]!==-1&&(k+=n[1].length)}}}a=a.substring(f.length,a.length-f.length);return[a,e]}
function Ba(d,b){for(var a=d.C,f="",c=1;c<=a;c++)f+=String.fromCharCode(c);for(c=0;c<b.length;c++)b[c].A+=a,b[c].i+=a;var c=b[0],e=c.b;if(e.length==0||e[0][0]!=0)e.unshift([0,f]),c.A-=a,c.i-=a,c.g+=a,c.k+=a;else if(a>e[0][1].length){var g=a-e[0][1].length;e[0][1]=f.substring(e[0][1].length)+e[0][1];c.A-=g;c.i-=g;c.g+=g;c.k+=g}c=b[b.length-1];e=c.b;e.length==0||e[e.length-1][0]!=0?(e.push([0,f]),c.g+=a,c.k+=a):a>e[e.length-1][1].length&&(g=a-e[e.length-1][1].length,e[e.length-1][1]+=f.substring(0,
g),c.g+=g,c.k+=g);return f}
function Ca(d,b){for(var a=d.l,f=0;f<b.length;f++)if(b[f].g>a){var c=b[f];b.splice(f--,1);for(var e=c.A,g=c.i,h="";c.b.length!==0;){var k=new T,i=!0;k.A=e-h.length;k.i=g-h.length;if(h!=="")k.g=k.k=h.length,k.b.push([0,h]);for(;c.b.length!==0&&k.g<a-d.C;){var h=c.b[0][0],j=c.b[0][1];h===1?(k.k+=j.length,g+=j.length,k.b.push(c.b.shift()),i=!1):h===-1&&k.b.length==1&&k.b[0][0]==0&&j.length>2*a?(k.g+=j.length,e+=j.length,i=!1,k.b.push([h,j]),c.b.shift()):(j=j.substring(0,a-k.g-d.C),k.g+=j.length,e+=j.length,
h===0?(k.k+=j.length,g+=j.length):i=!1,k.b.push([h,j]),j==c.b[0][1]?c.b.shift():c.b[0][1]=c.b[0][1].substring(j.length))}h=ra(k.b);h=h.substring(h.length-d.C);j=O(c.b).substring(0,d.C);j!==""&&(k.g+=j.length,k.k+=j.length,k.b.length!==0&&k.b[k.b.length-1][0]===0?k.b[k.b.length-1][1]+=j:k.b.push([0,j]));i||b.splice(++f,0,k)}}}function T(){this.b=[];this.i=this.A=x;this.k=this.g=0}
T.prototype.toString=function(){for(var d=["@@ -"+(this.g===0?this.A+",0":this.g==1?this.A+1:this.A+1+","+this.g)+" +"+(this.k===0?this.i+",0":this.k==1?this.i+1:this.i+1+","+this.k)+" @@\n"],b,a=0;a<this.b.length;a++){switch(this.b[a][0]){case 1:b="+";break;case -1:b="-";break;case 0:b=" "}d[a+1]=b+encodeURI(this.b[a][1])+"\n"}return d.join("").replace(/%20/g," ")};this.diff_match_patch=aa;this.DIFF_DELETE=-1;this.DIFF_INSERT=1;this.DIFF_EQUAL=0;/*
 The MIT license.
 @copyright Copyright (c) 2010 LearnBoost <dev@learnboost.com>
 The MIT license.
 @copyright Copyright (c) 2010 LearnBoost <dev@learnboost.com>
 The MIT license.
 @copyright Copyright (c) 2010 LearnBoost <dev@learnboost.com>
 The MIT license.
 @copyright Copyright (c) 2010 LearnBoost <dev@learnboost.com>
 The MIT license.
 @copyright Copyright (c) 2010 LearnBoost <dev@learnboost.com>
 The MIT license.
 @copyright Copyright (c) 2010 LearnBoost <dev@learnboost.com>
 The MIT license.
 @copyright Copyright (c) 2010 LearnBoost <dev@learnboost.com>
 The MIT license.
 @copyright Copyright (c) 2010 LearnBoost <dev@learnboost.com>
 The MIT license.
 @copyright Copyright (c) 2010 LearnBoost <dev@learnboost.com>
 The MIT license.
 @copyright Copyright (c) 2010 LearnBoost <dev@learnboost.com>
 The MIT license.
 @copyright Copyright (c) 2010 LearnBoost <dev@learnboost.com>
*/
var Da=this.z={version:"0.6.2",Dd:function(d){window.console&&console.error&&console.error("io.setPath will be removed. Please set the variable WEB_SOCKET_SWF_LOCATION pointing to WebSocketMain.swf");this.path=/\/$/.test(d)?d:d+"/";WEB_SOCKET_SWF_LOCATION=d+"lib/vendor/web-socket-js/WebSocketMain.swf"}};if("jQuery"in this)jQuery.z=this.z;typeof window!="undefined"&&typeof WEB_SOCKET_SWF_LOCATION==="undefined"&&(WEB_SOCKET_SWF_LOCATION="/socket.io/lib/vendor/web-socket-js/WebSocketMain.swf");
(function(){var d=this.z,b=!1;d.j={fc:!1,load:function(a){if(/loaded|complete/.test(document.readyState)||b)return a();"attachEvent"in window?window.attachEvent("onload",a):window.addEventListener("load",a,!1)},fa:function(a,b){for(var c in b.prototype)a.prototype[c]=b.prototype[c]},indexOf:function(a,b,c){for(var e=a.length,c=c<0?Math.max(0,e+c):c||0;c<e;c++)if(a[c]===b)return c;return-1},isArray:function(a){return Object.prototype.toString.call(a)==="[object Array]"},merge:function(a,b){for(var c in b)b.hasOwnProperty(c)&&
(a[c]=b[c])}};d.j.fc=/iphone|ipad/i.test(navigator.userAgent);d.j.Ic=/android/i.test(navigator.userAgent);d.j.opera=/opera/i.test(navigator.userAgent);d.j.load(function(){b=!0})})();
(function(){var d=this.z;Transport=d.d=function(b,a){this.r=b;this.options={timeout:15E3};d.j.merge(this.options,a)};Transport.prototype.send=function(){l(Error("Missing send() implementation"))};Transport.prototype.p=function(){l(Error("Missing connect() implementation"))};Transport.prototype.N=function(){l(Error("Missing disconnect() implementation"))};Transport.prototype.Sb=function(b){for(var a="",f,b=d.j.isArray(b)?b:[b],c=0,e=b.length;c<e;c++)b[c]===x||b[c]===void 0?f="":(f=b[c],Object.prototype.toString.call(f)==
"[object Object]"?"JSON"in window?f="~j~"+JSON.stringify(f):("console"in window&&console.error&&console.error("Trying to encode as JSON, but JSON.stringify is missing."),f='{ "$error": "Invalid message" }'):f=String(f)),a+="~m~"+f.length+"~m~"+f;return a};Transport.prototype.vc=function(b){var a=[],d,c;do{if(b.substr(0,3)!=="~m~")break;b=b.substr(3);d="";for(var e=0,g=b.length;e<g;e++)if(c=Number(b.substr(e,1)),b.substr(e,1)==c)d+=c;else{b=b.substr(d.length+3);d=Number(d);break}a.push(b.substr(0,
d));b=b.substr(d)}while(b!=="");return a};Transport.prototype.mb=function(b){this.Wb();if((b=this.vc(b))&&b.length)for(var a=0,d=b.length;a<d;a++)this.Na(b[a])};Transport.prototype.Wb=function(){var b=this;this.Xb&&clearTimeout(this.Xb);this.Xb=setTimeout(function(){b.Cc()},this.options.timeout)};Transport.prototype.Cc=function(){this.G()};Transport.prototype.Na=function(b){this.oa?b.substr(0,3)=="~h~"?this.Ac(b.substr(3)):b.substr(0,3)=="~j~"?this.r.Na(JSON.parse(b.substr(3))):this.r.Na(b):(this.oa=
b,this.lb())};Transport.prototype.Ac=function(b){this.send("~h~"+b)};Transport.prototype.lb=function(){this.m=!0;this.da=!1;this.r.lb();this.Wb()};Transport.prototype.G=function(){this.m=this.da=!1;this.oa=x;this.r.G()};Transport.prototype.ka=function(){return(this.r.options.Hb?"https":"http")+"://"+this.r.host+":"+this.r.options.port+"/"+this.r.options.Gb+"/"+this.type+(this.oa?"/"+this.oa:"/")};d.d=Transport})();
(function(){function d(e){if("XDomainRequest"in window&&e)return new XDomainRequest;if("XMLHttpRequest"in window&&(!e||f))return new XMLHttpRequest;if(!e){try{return new ActiveXObject("MSXML2.XMLHTTP")}catch(a){}try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(c){}}return!1}var b=this.z,a=new Function,f=!("XMLHttpRequest"in window)?!1:(new XMLHttpRequest).withCredentials!=void 0,c=b.d.XHR=function(){b.d.apply(this,arguments);this.ca=[]};b.j.fa(c,b.d);c.prototype.p=function(){this.qa();return this};
c.prototype.cb=function(){if(!this.Oa&&this.ca.length){var e=this.Sb(this.ca);this.ca=[];this.Vb(e)}};c.prototype.send=function(e){b.j.isArray(e)?this.ca.push.apply(this.ca,e):this.ca.push(e);this.cb();return this};c.prototype.Vb=function(e){var c=this;this.Oa=!0;this.L=this.nb("send","POST");this.L.onreadystatechange=function(){var e;if(c.L.readyState==4){c.L.onreadystatechange=a;try{e=c.L.status}catch(b){}c.Oa=!1;e==200?c.cb():c.G()}};this.L.send("data="+encodeURIComponent(e))};c.prototype.N=function(){this.G();
return this};c.prototype.G=function(){if(this.n){this.n.onreadystatechange=a;try{this.n.abort()}catch(e){}this.n=x}if(this.L){this.L.onreadystatechange=a;try{this.L.abort()}catch(c){}this.L=x}this.ca=[];b.d.prototype.G.call(this)};c.prototype.nb=function(e,a,c){var b=d(this.r.Tb());if(c)b.ud=!0;b.open(a||"GET",this.ka()+(e?"/"+e:""));if("withCredentials"in b)b.withCredentials="true";a=="POST"&&"setRequestHeader"in b&&b.setRequestHeader("Content-type","application/x-www-form-urlencoded; charset=utf-8");
return b};c.H=function(e){try{if(d(e))return!0}catch(a){}return!1};c.X=function(){return c.H(!0)};c.zd=d})();
(function(){var d=this.z;WebSocket=window.WebSocket;var b=d.d.websocket=function(){d.d.apply(this,arguments)};d.j.fa(b,d.d);b.prototype.type="websocket";b.prototype.p=function(){var a=this;this.ia=new WebSocket(this.ka());this.ia.onmessage=function(b){a.mb(b.data)};this.ia.onclose=function(){a.yc()};this.ia.onerror=function(b){a.zc(b)};return this};b.prototype.send=function(a){this.ia&&this.ia.send(this.Sb(a));return this};b.prototype.N=function(){this.ia&&this.ia.close();return this};b.prototype.yc=
function(){this.G()};b.prototype.zc=function(a){this.r.O("error",[a])};b.prototype.ka=function(){return(this.r.options.Hb?"wss":"ws")+"://"+this.r.host+":"+this.r.options.port+"/"+this.r.options.Gb+"/"+this.type+(this.oa?"/"+this.oa:"")};b.H=function(){if("MozWebSocket"in window)WebSocket=window.WebSocket=window.MozWebSocket;return"WebSocket"in window&&WebSocket.prototype&&WebSocket.prototype.send&&!!WebSocket.prototype.send.toString().match(/native/i)&&typeof WebSocket!=="undefined"};b.X=E(!0)})();
(function(){var d=this.z,b=d.d.flashsocket=function(){d.d.websocket.apply(this,arguments)};d.j.fa(b,d.d.websocket);b.prototype.type="flashsocket";b.prototype.p=function(){var a=this,b=arguments;WebSocket.Fa(function(){d.d.websocket.prototype.p.apply(a,b)});return this};b.prototype.send=function(){var a=this,b=arguments;WebSocket.Fa(function(){d.d.websocket.prototype.send.apply(a,b)});return this};b.H=function(){if(typeof WebSocket=="undefined"||!("__addTask"in WebSocket))return!1;if(d.j.opera)return!1;
if("navigator"in window&&"plugins"in navigator&&navigator.plugins["Shockwave Flash"])return!!navigator.plugins["Shockwave Flash"].description;if("ActiveXObject"in window)try{return!!(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version")}catch(a){}return!1};b.X=E(!0)})();
(function(){var d=this.z,b=d.d.htmlfile=function(){d.d.XHR.apply(this,arguments)};d.j.fa(b,d.d.XHR);b.prototype.type="htmlfile";b.prototype.qa=function(){var a=this;this.Dc();window.attachEvent("onunload",function(){a.Rb()})};b.prototype.Dc=function(){this.Q=new ActiveXObject("htmlfile");this.Q.open();this.Q.write("<html></html>");this.Q.parentWindow.Ad=this;this.Q.close();var a=this.Q.createElement("div");this.Q.body.appendChild(a);this.F=this.Q.createElement("iframe");a.appendChild(this.F);this.F.src=
this.ka()+"/"+ +new Date};b.prototype.Rb=function(){if(this.F)this.F.src="about:blank",this.Q=x,CollectGarbage()};b.prototype.N=function(){this.Rb();return d.d.XHR.prototype.N.call(this)};b.H=function(){if("ActiveXObject"in window)try{return new ActiveXObject("htmlfile")&&d.d.XHR.H()}catch(a){}return!1};b.X=E(!1)})();
(function(){var d=this.z,b=d.d["xhr-multipart"]=function(){d.d.XHR.apply(this,arguments)};d.j.fa(b,d.d.XHR);b.prototype.type="xhr-multipart";b.prototype.qa=function(){var a=this;this.n=this.nb("","GET",!0);this.n.onreadystatechange=function(){a.n.readyState==4&&a.mb(a.n.responseText)};this.n.send(x)};b.H=function(){return"XMLHttpRequest"in window&&"prototype"in XMLHttpRequest&&"multipart"in XMLHttpRequest.prototype};b.X=E(!0)})();
(function(){var d=this.z,b=new Function,a=d.d["xhr-polling"]=function(){d.d.XHR.apply(this,arguments)};d.j.fa(a,d.d.XHR);a.prototype.type="xhr-polling";a.prototype.p=function(){if(d.j.fc||d.j.Ic){var a=this;d.j.load(function(){setTimeout(function(){d.d.XHR.prototype.p.call(a)},10)})}else d.d.XHR.prototype.p.call(this)};a.prototype.qa=function(){var a=this;this.n=this.nb(+new Date,"GET");this.n.onreadystatechange=function(){var c;if(a.n.readyState==4){a.n.onreadystatechange=b;try{c=a.n.status}catch(e){}c==
200?(a.mb(a.n.responseText),a.qa()):a.G()}};this.n.send(x)};a.H=function(){return d.d.XHR.H()};a.X=function(){return d.d.XHR.X()}})();
(function(){var d=this.z;d.Mb=[];JSONPPolling=d.d["jsonp-polling"]=function(){d.d.XHR.apply(this,arguments);this.Ka=document.getElementsByTagName("script")[0];this.ib=d.Mb.length;d.Mb.push(this)};d.j.fa(JSONPPolling,d.d["xhr-polling"]);JSONPPolling.prototype.type="jsonp-polling";JSONPPolling.prototype.Vb=function(b){function a(){d();c.Oa=!1;c.cb()}function d(){c.F&&c.gb.removeChild(c.F);try{k=document.createElement('<iframe name="'+c.hb+'">')}catch(e){k=document.createElement("iframe"),k.name=c.hb}k.id=
c.hb;c.gb.appendChild(k);c.F=k}var c=this;if(!("_form"in this)){var e=document.createElement("FORM"),g=document.createElement("TEXTAREA"),h=this.hb="socket_io_iframe_"+this.ib,k;e.style.position="absolute";e.style.top="-1000px";e.style.left="-1000px";e.target=h;e.method="POST";e.action=this.ka()+"/"+ +new Date+"/"+this.ib;g.name="data";e.appendChild(g);this.Ka.parentNode.insertBefore(e,this.Ka);document.body.appendChild(e);this.gb=e;this.uc=g}d();this.Oa=!0;this.uc.value=b;try{this.gb.submit()}catch(i){}this.F.attachEvent?
k.onreadystatechange=function(){c.F.readyState=="complete"&&a()}:this.F.onload=a};JSONPPolling.prototype.qa=function(){var b=this,a=document.createElement("SCRIPT");if(this.Ra)this.Ra.parentNode.removeChild(this.Ra),this.Ra=x;a.async=!0;a.src=this.ka()+"/"+ +new Date+"/"+this.ib;a.onerror=function(){b.G()};this.Ka.parentNode.insertBefore(a,this.Ka);this.Ra=a};JSONPPolling.H=E(!0);JSONPPolling.X=E(!0)})();
(function(){var d=this.z,b=d.nc=function(a,b){this.host=a||document.domain;this.options={Hb:!1,document:document,port:document.location.port||80,Gb:"socket.io",Za:["websocket","flashsocket","htmlfile","xhr-multipart","xhr-polling","jsonp-polling"],Vc:{"xhr-polling":{timeout:25E3},"jsonp-polling":{timeout:25E3}},Zb:5E3,Eb:!0,U:500,Oc:10,Ea:!0,Ba:!0};d.j.merge(this.options,b);this.da=this.m=!1;this.K={};this.s=this.wb();!this.s&&"console"in window&&console.error("No transport available")};b.prototype.wb=
function(a){var b=a||this.options.Za;if(this.options.Ba&&!a&&(a=this.options.document.cookie.match("(?:^|;)\\s*socketio=([^;]*)")))this.Fc=!0,b=[decodeURIComponent(a[1])];for(var a=0,c;c=b[a];a++)if(d.d[c]&&d.d[c].H()&&(!this.Tb()||d.d[c].X()))return new d.d[c](this,this.options.Vc[c]||{});return x};b.prototype.p=function(){if(this.s&&!this.m&&(this.da&&this.N(!0),this.da=!0,this.O("connecting",[this.s.type]),this.s.p(),this.options.Zb)){var a=this;this.$b=setTimeout(function(){if(!a.m){a.N(!0);if(a.options.Ea&&
!a.Fc){if(!a.aa)a.aa=a.options.Za.slice(0);for(var b=a.aa;b.length>0&&b.splice(0,1)[0]!=a.s.type;);if(b.length)a.s=a.wb(b),a.p()}(!a.aa||a.aa.length==0)&&a.O("connect_failed")}a.aa&&a.aa.length==0&&delete a.aa},this.options.Zb)}return this};b.prototype.send=function(a){if(!this.s||!this.s.m)return this.Ec(a);this.s.send(a);return this};b.prototype.N=function(a){this.$b&&clearTimeout(this.$b);if(!a)this.options.Eb=!1;this.s.N();return this};b.prototype.ha=function(a,b){a in this.K||(this.K[a]=[]);
this.K[a].push(b)};b.prototype.O=function(a,b){if(a in this.K)for(var c=this.K[a].concat(),e=0,g=c.length;e<g;e++)c[e].apply(this,b===void 0?[]:b)};b.prototype.removeEvent=function(a,b){if(a in this.K)for(var c=0,e=this.K[a].length;c<e;c++)this.K[a][c]==b&&this.K[a].splice(c,1);return this};b.prototype.Ec=function(a){if(!("_queueStack"in this))this.ra=[];this.ra.push(a);return this};b.prototype.wc=function(){if("_queueStack"in this&&this.ra.length)this.s.send(this.ra),this.ra=[]};b.prototype.Tb=function(){var a=
window.location.port||80;return this.host!==document.domain||this.options.port!=a};b.prototype.lb=function(){this.m=!0;this.da=!1;this.wc();if(this.options.Ba)this.options.document.cookie="socketio="+encodeURIComponent(this.s.type);this.O("connect")};b.prototype.Na=function(a){this.O("message",[a])};b.prototype.G=function(){var a=this.m;this.da=this.m=!1;this.ra=[];a&&(this.O("disconnect"),this.options.Eb&&!this.Xa&&this.Bc())};b.prototype.Bc=function(){function a(){c.m&&c.O("reconnect",[c.s.type,
c.Ya]);c.removeEvent("connect_failed",b).removeEvent("connect",b);delete c.Xa;delete c.Ya;delete c.U;delete c.Fb;delete c.kc;c.options.Ea=e;c.options.Ba=g}function b(){if(c.Xa)if(c.m)a();else{if(c.da&&c.Xa)return c.Fb=setTimeout(b,1E3);c.Ya++>=c.options.Oc?c.kc?(c.O("reconnect_failed"),a()):(c.ha("connect_failed",b),c.options.Ea=!0,c.s=c.wb(c.options.Za),c.kc=!0,c.p()):(c.U*=2,c.p(),c.O("reconnecting",[c.U,c.Ya]),c.Fb=setTimeout(b,c.U))}}this.Xa=!0;this.Ya=0;this.U=this.options.U;var c=this,e=this.options.Ea,
g=this.options.Ba;this.options.Ea=!1;this.Fb=setTimeout(b,this.U);this.ha("connect",b)}})();
var Z=function(){function d(){if(!H){try{var e=s.getElementsByTagName("body")[0].appendChild(s.createElement("span"));e.parentNode.removeChild(e)}catch(a){return}H=!0;for(var e=V.length,c=0;c<e;c++)V[c]()}}function b(e){H?e():V[V.length]=e}function a(e){if(typeof C.addEventListener!=q)C.addEventListener("load",e,!1);else if(typeof s.addEventListener!=q)s.addEventListener("load",e,!1);else if(typeof C.attachEvent!=q)p(C,e);else if(typeof C.onload=="function"){var a=C.onload;C.onload=function(){a();
e()}}else C.onload=e}function f(){var e=s.getElementsByTagName("body")[0],a=s.createElement(v);a.setAttribute("type",B);var b=e.appendChild(a);if(b){var g=0;(function(){if(typeof b.GetVariable!=q){var h=b.GetVariable("$version");if(h)h=h.split(" ")[1].split(","),o.na=[parseInt(h[0],10),parseInt(h[1],10),parseInt(h[2],10)]}else if(g<10){g++;setTimeout(arguments.callee,10);return}e.removeChild(a);b=x;c()})()}else c()}function c(){var a=F.length;if(a>0)for(var c=0;c<a;c++){var b=F[c].id,d=F[c].Kc,f=
{success:!1,id:b};if(o.na[0]>0){var i=n(b);if(i)if(r(F[c].Uc)&&!(o.P&&o.P<312)){if(t(b,!0),d)f.success=!0,f.lc=e(b),d(f)}else if(F[c].dc&&g()){f={};f.data=F[c].dc;f.width=i.getAttribute("width")||"0";f.height=i.getAttribute("height")||"0";if(i.getAttribute("class"))f.Fd=i.getAttribute("class");if(i.getAttribute("align"))f.align=i.getAttribute("align");for(var j={},i=i.getElementsByTagName("param"),m=i.length,p=0;p<m;p++)i[p].getAttribute("name").toLowerCase()!="movie"&&(j[i[p].getAttribute("name")]=
i[p].getAttribute("value"));h(f,j,b,d)}else k(i),d&&d(f)}else if(t(b,!0),d){if((b=e(b))&&typeof b.SetVariable!=q)f.success=!0,f.lc=b;d(f)}}}function e(e){var a=x;if((e=n(e))&&e.nodeName=="OBJECT")typeof e.SetVariable!=q?a=e:(e=e.getElementsByTagName(v)[0])&&(a=e);return a}function g(){return!W&&r("6.0.65")&&(o.B||o.hc)&&!(o.P&&o.P<312)}function h(e,a,c,b){W=!0;ba=b||x;ta={success:!1,id:c};var g=n(c);if(g){g.nodeName=="OBJECT"?(Q=i(g),X=x):(Q=g,X=c);e.id=y;if(typeof e.width==q||!/%$/.test(e.width)&&
parseInt(e.width,10)<310)e.width="310";if(typeof e.height==q||!/%$/.test(e.height)&&parseInt(e.height,10)<137)e.height="137";s.title=s.title.slice(0,47)+" - Flash Player Installation";b=o.w&&o.B?"ActiveX":"PlugIn";b="MMredirectURL="+C.location.toString().replace(/&/g,"%26")+"&MMplayerType="+b+"&MMdoctitle="+s.title;typeof a.ya!=q?a.ya+="&"+b:a.ya=b;if(o.w&&o.B&&g.readyState!=4)b=s.createElement("div"),c+="SWFObjectNew",b.setAttribute("id",c),g.parentNode.insertBefore(b,g),g.style.display="none",function(){g.readyState==
4?g.parentNode.removeChild(g):setTimeout(arguments.callee,10)}();j(e,a,c)}}function k(e){if(o.w&&o.B&&e.readyState!=4){var a=s.createElement("div");e.parentNode.insertBefore(a,e);a.parentNode.replaceChild(i(e),a);e.style.display="none";(function(){e.readyState==4?e.parentNode.removeChild(e):setTimeout(arguments.callee,10)})()}else e.parentNode.replaceChild(i(e),e)}function i(e){var a=s.createElement("div");if(o.B&&o.w)a.innerHTML=e.innerHTML;else if(e=e.getElementsByTagName(v)[0])if(e=e.childNodes)for(var c=
e.length,b=0;b<c;b++)!(e[b].nodeType==1&&e[b].nodeName=="PARAM")&&e[b].nodeType!=8&&a.appendChild(e[b].cloneNode(!0));return a}function j(e,a,c){var b,g=n(c);if(o.P&&o.P<312)return b;if(g){if(typeof e.id==q)e.id=c;if(o.w&&o.B){var h="",d;for(d in e)if(e[d]!=Object.prototype[d])d.toLowerCase()=="data"?a.sd=e[d]:d.toLowerCase()=="styleclass"?h+=' class="'+e[d]+'"':d.toLowerCase()!="classid"&&(h+=" "+d+'="'+e[d]+'"');d="";for(var f in a)a[f]!=Object.prototype[f]&&(d+='<param name="'+f+'" value="'+a[f]+
'" />');g.outerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+h+">"+d+"</object>";Y[Y.length]=e.id;b=n(e.id)}else{f=s.createElement(v);f.setAttribute("type",B);for(var k in e)e[k]!=Object.prototype[k]&&(k.toLowerCase()=="styleclass"?f.setAttribute("class",e[k]):k.toLowerCase()!="classid"&&f.setAttribute(k,e[k]));for(h in a)a[h]!=Object.prototype[h]&&h.toLowerCase()!="movie"&&(e=f,d=h,k=a[h],c=s.createElement("param"),c.setAttribute("name",d),c.setAttribute("value",k),e.appendChild(c));
g.parentNode.replaceChild(f,g);b=f}}return b}function m(e){var a=n(e);if(a&&a.nodeName=="OBJECT")o.w&&o.B?(a.style.display="none",function(){if(a.readyState==4){var c=n(e);if(c){for(var b in c)typeof c[b]=="function"&&(c[b]=x);c.parentNode.removeChild(c)}}else setTimeout(arguments.callee,10)}()):a.parentNode.removeChild(a)}function n(e){var a=x;try{a=s.getElementById(e)}catch(c){}return a}function p(e,a){e.attachEvent("onload",a);N[N.length]=[e,"onload",a]}function r(e){var a=o.na,e=e.split(".");
e[0]=parseInt(e[0],10);e[1]=parseInt(e[1],10)||0;e[2]=parseInt(e[2],10)||0;return a[0]>e[0]||a[0]==e[0]&&a[1]>e[1]||a[0]==e[0]&&a[1]==e[1]&&a[2]>=e[2]?!0:!1}function w(e,a,c,b){if(!o.w||!o.hc){var g=s.getElementsByTagName("head")[0];if(g){c=c&&typeof c=="string"?c:"screen";b&&(ca=D=x);if(!D||ca!=c)b=s.createElement("style"),b.setAttribute("type","text/css"),b.setAttribute("media",c),D=g.appendChild(b),o.w&&o.B&&typeof s.styleSheets!=q&&s.styleSheets.length>0&&(D=s.styleSheets[s.styleSheets.length-
1]),ca=c;o.w&&o.B?D&&typeof D.addRule==v&&D.addRule(e,a):D&&typeof s.createTextNode!=q&&D.appendChild(s.createTextNode(e+" {"+a+"}"))}}}function t(e,a){if(ua){var c=a?"visible":"hidden";H&&n(e)?n(e).style.visibility=c:w("#"+e,"visibility:"+c)}}function u(e){return/[\\\"<>\.;]/.exec(e)!=x&&typeof encodeURIComponent!=q?encodeURIComponent(e):e}var q="undefined",v="object",B="application/x-shockwave-flash",y="SWFObjectExprInst",C=window,s=document,G=navigator,va=!1,V=[function(){va?f():c()}],F=[],Y=[],
N=[],Q,X,ba,ta,H=!1,W=!1,D,ca,ua=!0,o=function(){var e=typeof s.getElementById!=q&&typeof s.getElementsByTagName!=q&&typeof s.createElement!=q,a=G.userAgent.toLowerCase(),c=G.platform.toLowerCase(),b=c?/win/.test(c):/win/.test(a),c=c?/mac/.test(c):/mac/.test(a),a=/webkit/.test(a)?parseFloat(a.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):!1,g=!+"\u000b1",h=[0,0,0],d=x;if(typeof G.plugins!=q&&typeof G.plugins["Shockwave Flash"]==v){if((d=G.plugins["Shockwave Flash"].description)&&!(typeof G.mimeTypes!=
q&&G.mimeTypes[B]&&!G.mimeTypes[B].enabledPlugin))va=!0,g=!1,d=d.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),h[0]=parseInt(d.replace(/^(.*)\..*$/,"$1"),10),h[1]=parseInt(d.replace(/^.*\.(.*)\s.*$/,"$1"),10),h[2]=/[a-zA-Z]/.test(d)?parseInt(d.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),10):0}else if(typeof C.ActiveXObject!=q)try{var f=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");if(f&&(d=f.GetVariable("$version")))g=!0,d=d.split(" ")[1].split(","),h=[parseInt(d[0],10),parseInt(d[1],10),parseInt(d[2],10)]}catch(k){}return{W:e,
na:h,P:a,w:g,B:b,hc:c}}();(function(){o.W&&((typeof s.readyState!=q&&s.readyState=="complete"||typeof s.readyState==q&&(s.getElementsByTagName("body")[0]||s.body))&&d(),H||(typeof s.addEventListener!=q&&s.addEventListener("DOMContentLoaded",d,!1),o.w&&o.B&&(s.attachEvent("onreadystatechange",function(){s.readyState=="complete"&&(s.detachEvent("onreadystatechange",arguments.callee),d())}),C==top&&function(){if(!H){try{s.documentElement.doScroll("left")}catch(e){setTimeout(arguments.callee,0);return}d()}}()),
o.P&&function(){H||(/loaded|complete/.test(s.readyState)?d():setTimeout(arguments.callee,0))}(),a(d)))})();(function(){o.w&&o.B&&window.attachEvent("onunload",function(){for(var e=N.length,a=0;a<e;a++)N[a][0].detachEvent(N[a][1],N[a][2]);e=Y.length;for(a=0;a<e;a++)m(Y[a]);for(var c in o)o[c]=x;o=x;for(var b in Z)Z[b]=x;Z=x})})();return{wd:function(e,a,c,b){if(o.W&&e&&a){var g={};g.id=e;g.Uc=a;g.dc=c;g.Kc=b;F[F.length]=g;t(e,!1)}else b&&b({success:!1,id:e})},ld:function(a){if(o.W)return e(a)},Mc:function(e,
a,c,d,f,k,i,m,n,p){var u={success:!1,id:a};o.W&&!(o.P&&o.P<312)&&e&&a&&c&&d&&f?(t(a,!1),b(function(){c+="";d+="";var b={};if(n&&typeof n===v)for(var o in n)b[o]=n[o];b.data=e;b.width=c;b.height=d;o={};if(m&&typeof m===v)for(var s in m)o[s]=m[s];if(i&&typeof i===v)for(var w in i)typeof o.ya!=q?o.ya+="&"+w+"="+i[w]:o.ya=w+"="+i[w];if(r(f))s=j(b,o,a),b.id==a&&t(a,!0),u.success=!0,u.lc=s;else if(k&&g()){b.data=k;h(b,o,a,p);return}else t(a,!0);p&&p(u)})):p&&p(u)},Gd:function(){ua=!1},Id:o,kd:function(){return{qd:o.na[0],
rd:o.na[1],xd:o.na[2]}},Nc:r,hd:function(e,a,c){if(o.W)return j(e,a,c)},Ed:function(e,a,c,b){o.W&&g()&&h(e,a,c,b)},yd:function(e){o.W&&m(e)},gd:function(e,a,c,b){o.W&&w(e,a,c,b)},cd:b,dd:a,md:function(e){var a=s.location.search||s.location.hash;if(a){/\?/.test(a)&&(a=a.split("?")[1]);if(e==x)return u(a);for(var a=a.split("&"),c=0;c<a.length;c++)if(a[c].substring(0,a[c].indexOf("="))==e)return u(a[c].substring(a[c].indexOf("=")+1))}return""},jd:function(){if(W){var e=n(y);if(e&&Q){e.parentNode.replaceChild(Q,
e);if(X&&(t(X,!0),o.w&&o.B))Q.style.display="block";ba&&ba(ta)}W=!1}}}}();
(function(){function d(){}if(!("WebSocket"in window)){var b=window.console;if(!b||!b.log||!b.error)b={log:A(),error:A()};Z.Nc("10.0.0")?(location.protocol=="file:"&&b.error("WARNING: web-socket-js doesn't work in file:///... URL unless you set Flash Security Settings properly. Open the page via Web server i.e. http://..."),WebSocket=function(a,b,c,e,g){var h=this;h.Ga=WebSocket.sc++;WebSocket.Qb[h.Ga]=h;h.readyState=WebSocket.CONNECTING;h.bufferedAmount=0;setTimeout(function(){WebSocket.Fa(function(){WebSocket.D.create(h.Ga,
a,b,c||x,e||0,g||x)})},0)},WebSocket.prototype.send=function(a){this.readyState==WebSocket.CONNECTING&&l("INVALID_STATE_ERR: Web Socket connection has not been established");a=WebSocket.D.send(this.Ga,encodeURIComponent(a));return a<0?!0:(this.bufferedAmount+=a,!1)},WebSocket.prototype.close=function(){if(!(this.readyState==WebSocket.CLOSED||this.readyState==WebSocket.Kb))this.readyState=WebSocket.Kb,WebSocket.D.close(this.Ga)},WebSocket.prototype.addEventListener=function(a,b){if(!("__events"in this))this.J=
{};if(!(a in this.J)&&(this.J[a]=[],"function"==typeof this["on"+a]))this.J[a].bc=this["on"+a],this["on"+a]=this.pc(this,a);this.J[a].push(b)},WebSocket.prototype.dispatchEvent=function(a){"__events"in this||l("UNSPECIFIED_EVENT_TYPE_ERR");a.type in this.J||l("UNSPECIFIED_EVENT_TYPE_ERR");for(var b=0,c=this.J[a.type].length;b<c;++b)if(this.J[a.type][b](a),a.cancelBubble)break;!1!==a.returnValue&&"function"==typeof this.J[a.type].bc&&this.J[a.type].bc(a)},WebSocket.prototype.qc=function(a){if("readyState"in
a)this.readyState=a.readyState;try{if(a.type=="open")this.onopen&&this.onopen();else if(a.type=="close")this.onclose&&this.onclose();else if(a.type=="error")this.onerror&&this.onerror(a);else if(a.type=="message"){if(this.onmessage){var d=decodeURIComponent(a.message),c;window.Wc&&!window.opera?(c=document.createEvent("MessageEvent"),c.initMessageEvent("message",!1,!1,d,x,x,window,x)):c={data:d};this.onmessage(c)}}else l("unknown event type: "+a.type)}catch(e){b.error(e.toString())}},WebSocket.prototype.pc=
function(a,b){return function(c){var e=new d;e.initEvent(b,!0,!0);e.target=e.currentTarget=a;for(var g in c)e[g]=c[g];a.dispatchEvent(e,arguments)}},WebSocket.CONNECTING=0,WebSocket.OPEN=1,WebSocket.Kb=2,WebSocket.CLOSED=3,WebSocket.D=x,WebSocket.Qb={},WebSocket.Ha=[],WebSocket.sc=0,WebSocket.Pb=function(){if(!WebSocket.D){if(WebSocket.tc)window.oc=WebSocket.tc;if(window.oc){var a=document.createElement("div");a.id="webSocketContainer";a.style.position="absolute";WebSocket.rc()?(a.style.left="0px",
a.style.top="0px"):(a.style.left="-100px",a.style.top="-100px");var d=document.createElement("div");d.id="webSocketFlash";a.appendChild(d);document.body.appendChild(a);Z.Mc(WEB_SOCKET_SWF_LOCATION,"webSocketFlash","1","1","10.0.0",x,x,{nd:!0,Hd:!0,ed:"always"},x,function(a){a.success||b.error("[WebSocket] swfobject.embedSWF failed")})}else b.error("[WebSocket] set WEB_SOCKET_SWF_LOCATION to location of WebSocketMain.swf")}},WebSocket.od=function(a){WebSocket.Fa(function(){WebSocket.D.pd(a)})},WebSocket.bd=
function(){setTimeout(function(){WebSocket.D=document.getElementById("webSocketFlash");WebSocket.D.Bd(location.href);WebSocket.D.Cd(!!window.Xc);for(var a=0;a<WebSocket.Ha.length;++a)WebSocket.Ha[a]();WebSocket.Ha=[]},0)},WebSocket.ad=function(){setTimeout(function(){for(var a=WebSocket.D.vd(),b=0;b<a.length;++b)WebSocket.Qb[a[b].Kd].qc(a[b])},0);return!0},WebSocket.$c=function(a){b.log(decodeURIComponent(a))},WebSocket.Zc=function(a){b.error(decodeURIComponent(a))},WebSocket.Fa=function(a){WebSocket.D?
a():WebSocket.Ha.push(a)},WebSocket.rc=function(){if(!window.navigator||!window.navigator.mimeTypes)return!1;var a=window.navigator.mimeTypes["application/x-shockwave-flash"];return!a||!a.enabledPlugin||!a.enabledPlugin.filename?!1:a.enabledPlugin.filename.match(/flashlite/i)?!0:!1},d.prototype.cancelable=!0,d.prototype.cancelBubble=!1,d.prototype.initEvent=function(a,b,c){this.type=a;this.cancelable=c;this.timeStamp=new Date},window.Yc||(window.addEventListener?window.addEventListener("load",function(){WebSocket.Pb()},
!1):window.attachEvent("onload",function(){WebSocket.Pb()}))):b.error("Flash Player >= 10.0.0 is required.")}})();(function(){function d(a,c){return function(){return a.apply(c,arguments)}}var b,a=Object.prototype.hasOwnProperty;b=function(){function b(){this.Wa=d(this.Wa,this);this.Da=d(this.Da,this);this.Jb=d(this.Jb,this);this.ub=d(this.ub,this);this.R=d(this.R,this);this.ma=d(this.ma,this);this.xa=d(this.xa,this);this.Aa=d(this.Aa,this);this.gc=d(this.gc,this);this.fb=d(this.fb,this);this.eb=d(this.eb,this);this.Bb=d(this.Bb,this);this.yb=d(this.yb,this);this.u=d(this.u,this);this.q=d(this.q,this);this.V=
d(this.V,this);this.I=d(this.I,this)}b.c=new aa;b.prototype.I=function(b){var e,g;g=0;for(e in b)a.call(b,e)&&g++;return g};b.prototype.V=function(a){var e;e=typeof a;e==="object"&&(a?typeof a.length==="number"&&typeof a.splice==="function"&&!a.propertyIsEnumerable("length")&&(e="array"):e="null");return e};b.prototype.q=function(a){var e,b,h;if(Object.prototype.toString.call(a)==="[object Array]"){b=[];e=0;for(h=a.length;0<=h?e<h:e>h;0<=h?e++:e--)b[e]=arguments.callee(a[e]);return b}if(typeof a===
"object"){b={};for(e in a)b[e]=arguments.callee(a[e]);return b}return a};b.prototype.u=function(a,e){var b;b=this.V(a);return b!==this.V(e)?!1:b==="array"?this.yb(a,e):b==="object"?this.Bb(a,e):a===e};b.prototype.yb=function(a,e){var b,h;b=a.length;if(b!==e.length)return!1;for(h=0;0<=b?h<b:h>b;0<=b?h++:h--)if(!this.u(a[h],e[h]))return!1;return!0};b.prototype.Bb=function(b,e){for(var g in b)if(a.call(b,g)){if(!(g in e))return!1;if(!this.u(b[g],e[g]))return!1}for(g in e)if(a.call(e,g)&&!(g in b))return!1;
return!0};b.prototype.eb=function(a,e){var b,h;h=Math.min(a.length,e.length);for(b=0;0<=h?b<h:b>h;0<=h?b++:b--)if(!this.u(a[b],e[b]))return b;return h};b.prototype.fb=function(a,e){var b,h,d,i;h=a.length;d=e.length;i=Math.min(a.length,e.length);if(i===0)return 0;for(b=0;0<=i?b<i:b>i;0<=i?b++:b--)if(!this.u(a[h-b-1],e[d-b-1]))return b;return i};b.prototype.gc=function(a,e){var b,h,d,i,f,m;b={};d=a.length;i=e.length;m=this.eb(a,e);h=this.fb(a,e);a=a.slice(m,d-h);e=e.slice(m,i-h);d=a.length;i=e.length;
f=Math.max(d,i);for(h=0;0<=f?h<=f:h>=f;0<=f?h++:h--)h<d&&h<i?this.u(a[h],e[h])||(b[h+m]=this.xa(a[h],e[h])):h<d?b[h+m]={o:"-"}:h<i&&(b[h+m]={o:"+",v:e[h]});return b};b.prototype.Aa=function(b,e){var g,h;g={};if(b==x||e==x)return{};for(h in b)a.call(b,h)&&(h in e?this.u(b[h],e[h])||(g[h]=this.xa(b[h],e[h])):g[h]={o:"-"});for(h in e)a.call(e,h)&&(h in b||(g[h]={o:"+",v:e[h]}));return g};b.prototype.xa=function(a,e){var g;if(this.u(a,e))return{};g=this.V(a);if(g!==this.V(e))return{o:"r",v:e};switch(g){case "boolean":return{o:"r",
v:e};case "number":return{o:"r",v:e};case "array":return{o:"r",v:e};case "object":return{o:"O",v:this.Aa(a,e)};case "string":if(g=I(b.c,a,e),g.length>2&&qa(b.c,g),g.length>0)return{o:"d",v:wa(g)}}return{}};b.prototype.ma=function(c,e){var g,h,d,i,j,m,n,p,r;m=this.q(c);i=[];g=[];for(j in e)a.call(e,j)&&(i.push(j),i.sort());j=0;for(r=i.length;j<r;j++)switch(d=i[j],h=e[d],n=function(){var e,a,b;b=[];e=0;for(a=g.length;e<a;e++)p=g[e],p<=d&&b.push(p);return b}().length,n=d-n,h.o){case "+":[].splice.apply(m,
[n,n-n+1].concat(h.v));break;case "-":[].splice.apply(m,[n,n-n+1].concat([]));g[g.length]=n;break;case "r":m[n]=h.v;break;case "I":m[n]+=h.v;break;case "L":m[n]=this.ma(m[n],h.v);break;case "O":m[n]=this.R(m[n],h.v);break;case "d":h=P(m[n],h.v),h=S(b.c,m[n],h),h=U(b.c,h,m[n]),m[n]=h[0]}return m};b.prototype.R=function(c,e){var g,h,d;d=this.q(c);for(h in e)if(a.call(e,h))switch(g=e[h],g.o){case "+":d[h]=g.v;break;case "-":delete d[h];break;case "r":d[h]=g.v;break;case "I":d[h]+=g.v;break;case "L":d[h]=
this.ma(d[h],g.v);break;case "O":d[h]=this.R(d[h],g.v);break;case "d":g=P(d[h],g.v),g=S(b.c,d[h],g),g=U(b.c,g,d[h]),d[h]=g[0]}return d};b.prototype.ub=function(c,e,g,d){var k,i,c=this.q(c);for(i in e)if(a.call(e,i))switch(k=e[i],k.o){case "+":c[i]=k.v;break;case "-":delete c[i];break;case "r":c[i]=k.v;break;case "I":c[i]+=k.v;break;case "L":c[i]=this.ma(c[i],k.v);break;case "O":c[i]=this.R(c[i],k.v);break;case "d":k=P(c[i],k.v),k=S(b.c,c[i],k),i===g?c[i]=this.Wa(k,c[i],d):(k=U(b.c,k,c[i]),c[i]=k[0])}return c};
b.prototype.Jb=function(b,e,g){var d,k,i,f,m,n,p,r;d={};i=[];k=[];for(m in e)a.call(e,m)&&(f=e[m],f.o==="+"&&i.push(m),f.o==="-"&&k.push(m));for(m in b)if(a.call(b,m))f=b[m],p=[function(){var e,a,b;b=[];e=0;for(a=i.length;e<a;e++)r=i[e],r<=m&&b.push(r);return b}()].length,n=[function(){var e,a,b;b=[];e=0;for(a=k.length;e<a;e++)r=k[e],r<=m&&b.push(r);return b}()].length,m=m+p-n,n=String(m),d[n]=f,m in e&&!(f.o==="+"&&e.index.o==="+")&&(f.o==="-"&&e.index.o==="-"?delete d[n]:(f=this.Da({Tc:f},{Tc:e.index},
g),d[n]=f[n]));return d};b.prototype.Da=function(c,e,g){var d,k,i,j;k=this.q(c);for(j in c)if(a.call(c,j)&&(d=c[j],j in e)){c=g[j];e=e[j];if(d.o==="+"&&e.o==="+")this.u(d.v,e.v)?delete k[j]:k[j]=this.xa(e.v,d.v);else if(d.o==="-"&&e.o==="-")delete k[j];else if(e.o==="-"&&((i=d.o)==="O"||i==="L"||i==="I"||i==="d"))if(k[j]={o:"+"},d.o==="O")k[j].v=this.R(c,d.v);else if(d.o==="L")k[j].v=this.ma(c,d.v);else if(d.o==="I")k[j].v=c+d.v;else{if(d.o==="d")d=P(c,d.v),d=S(b.c,c,d),c=U(b.c,d,c),k[j].v=c[0]}else d.o===
"O"&&e.o==="O"?k[j]={o:"O",v:this.Da(d.v,e.v,c)}:d.o==="L"&&e.o==="L"?k[j]={o:"O",v:this.Jb(d.v,e.v,c)}:d.o==="d"&&e.o==="d"&&(delete k[j],d=S(b.c,c,P(c,d.v)),i=S(b.c,c,P(c,e.v)),c=U(b.c,i,c)[0],d=U(b.c,d,c)[0],d!==c&&(d=I(b.c,c,d),d.length>2&&qa(b.c,d),d.length>0&&(k[j]={o:"d",v:wa(d)})));return k}};b.prototype.Wa=A();b.prototype.Wa=function(a,e,d){if(a.length==0)return e;var a=Aa(a),h=Ba(b.c,a),e=h+e+h;Ca(b.c,a);for(var k=0,i=0;i<a.length;i++){var j=a[i].i+k,m=O(a[i].b),n,p=-1;if(m.length>b.c.l){if(n=
R(b.c,e,m.substring(0,b.c.l),j),n!=-1&&(p=R(b.c,e,m.substring(m.length-b.c.l),j+m.length-b.c.l),p==-1||n>=p))n=-1}else n=R(b.c,e,m,j);if(n==-1)k-=a[i].k-a[i].g;else if(k=n-j,j=I(b.c,m,p==-1?e.substring(n,n+m.length):e.substring(n,p+b.c.l),!1),!(m.length>b.c.l&&sa(j)/m.length>b.c.Ob))for(var m=0,r,p=0;p<a[i].b.length;p++){var w=a[i].b[p];w[0]!==0&&(r=M(j,m));if(w[0]===1)for(var e=e.substring(0,n+r)+w[1]+e.substring(n+r),t=0;t<d.length;t++)d[t]+h.length>n+r&&(d[t]+=w[1].length);else if(w[0]===-1)for(var u=
n+r,q=n+M(j,m+w[1].length),e=e.substring(0,u)+e.substring(q),t=0;t<d.length;t++)d[t]+h.length>u&&(d[t]+h.length<q?d[t]=u-h.length:d[t]-=q-u);w[0]!==-1&&(m+=w[1].length)}}return e=e.substring(h.length,e.length-h.length)};return b}();window.jsondiff=b}).call(this);(function(){function d(a,e){return function(){return a.apply(e,arguments)}}var b,a=Object.prototype.hasOwnProperty,f=Array.prototype.indexOf||function(a){for(var e=0,b=this.length;e<b;e++)if(e in this&&this[e]===a)return e;return-1};b=function(){function b(e,a,c){this.la=e;this.a=a;this.options=c;this.Qa=d(this.Qa,this);this.Ia=d(this.Ia,this);this.Cb=d(this.Cb,this);this.Ca=d(this.Ca,this);this.ta=d(this.ta,this);this.sa=d(this.sa,this);this.La=d(this.La,this);this.update=d(this.update,this);this.pa=
d(this.pa,this);this.Ma=d(this.Ma,this);this.rb=d(this.rb,this);this.qb=d(this.qb,this);this.ob=d(this.ob,this);this.sb=d(this.sb,this);this.pb=d(this.pb,this);this.Ja=d(this.Ja,this);this.Va=d(this.Va,this);this.ec=d(this.ec,this);this.zb=d(this.zb,this);this.jc=d(this.jc,this);this.Db=d(this.Db,this);this.Z=d(this.Z,this);this.start=d(this.start,this);this.Ua=d(this.Ua,this);this.xb=d(this.xb,this);this.get=d(this.get,this);this.bb=d(this.bb,this);this.Ab=d(this.Ab,this);this.Pa=d(this.Pa,this);
this.ba=d(this.ba,this);this.jb=d(this.jb,this);this.tb=d(this.tb,this);this.kb=d(this.kb,this);this.f=new jsondiff;this.c=jsondiff.c;this.S=x;this.options=this.options||{};this.namespace=""+this.la+"/"+this.a;"host"in this.options||(this.options.host="api.simperium.com");"port"in this.options||(this.options.port=80);"auth_host"in this.options||(this.options.auth_host="stargate.simperium.com");if("token"in this.options)this.S=this.options.token;"stream_index"in this.options||(this.options.stream_index=
!1);this.Jc=this.za=!1;a=this.options.host.indexOf("simperium.com")!==-1?"https":"http";e=this.options.auth_host.indexOf("simperium.com")!==-1?"https":"http";this.options.port=parseInt(this.options.port);this.ac=this.options.port!==80&&this.options.port!==443?""+a+"://"+this.options.host+":"+this.options.port+"/"+this.la+"/"+this.a+"/data":""+a+"://"+this.options.host+"/"+this.la+"/"+this.a+"/data";this.Yb=""+e+"://"+this.options.auth_host+"/app/"+this.la+"/authorize?response_type=token&client_id="+
this.options.client_id+"&redirect_uri="+window.location;console.log(""+this.a+": dataurl: "+this.ac);this.wa=x;if(this.wa==x)this.wa="smp-002-"+this.Y()+this.Y()+this.Y(),localStorage.setItem(""+this.la+"/clientid",this.wa);this.data={va:1,t:0,e:{}};this.M=[];"nostore"in this.options?(console.log(""+this.a+": not loading from localstorage"),this.loaded=0):("username"in this.options&&(e=localStorage.getItem(""+this.namespace+"/username"),e!=x&&e!==this.options.username&&localStorage.clear()),this.kb(),
this.loaded=this.jb(),console.log(""+this.a+": localstorage loaded "+this.loaded+" entities"));this.ic={};this.ua=this.Ta=this.vb=this.T=x}b.prototype.Y=function(){return((1+Math.random())*65536|0).toString(16).substring(1)};b.prototype.Hc=function(){var a;a=new Date;return Date.UTC(a.getUTCFullYear(),a.getUTCMonth(),a.getUTCDate(),a.getUTCHours(),a.getUTCMinutes(),a.getUTCSeconds(),a.getUTCMilliseconds())/1E3};b.prototype.Ib=function(){try{return"localStorage"in window&&window.localStorage!==x}catch(a){return!1}};
b.prototype.Ub=function(){if(this.Ib())try{localStorage.setItem(""+this.namespace+"/ccid",this.data.va),localStorage.setItem(""+this.namespace+"/last_cv",this.data.t)}catch(a){}};b.prototype.kb=function(){var a,b,c;if(this.Ib()){this.data.va=localStorage.getItem(""+this.namespace+"/ccid");if((a=this.data).va==x)a.va=1;this.data.t=localStorage.getItem(""+this.namespace+"/last_cv");return(c=(b=this.data).t)!=x?c:b.t=0}};b.prototype.tb=function(a){if(!("object"in a)||!("version"in a))return!1;if(this.f.I(a.object)===
0)return this.f.I(a.last)>0?!0:!1;else if(a.version==x)return!1;return!0};b.prototype.jb=function(){var b,c,d,k,i,f,m;if(this.Ib()){m=""+this.namespace+"/e/";f=m.length;i=0;for(k in localStorage)if(a.call(localStorage,k)&&(c=localStorage[k],k.substr(0,f)===m)){d=k.substr(f,k.length-f);try{b=JSON.parse(c)}catch(n){b=x}b!=x&&(this.tb(b)?("check"in b&&delete b.check,this.data.e[d]=b,i+=1):console.log("ignoring CORRUPT data: "+JSON.stringify(b)))}return i}};b.prototype.ba=function(a){var b,c;c=""+this.namespace+
"/e/"+a;a=this.data.e[a];b=JSON.stringify(a);try{localStorage.setItem(c,b)}catch(d){return!1}c=JSON.parse(localStorage.getItem(c));return this.f.u(a,c)?!0:!1};b.prototype.Pa=function(a){return localStorage.removeItem(""+this.namespace+"/e/"+a)};b.prototype.xc=function(){var a,b,c,d;a={};b=window.location.hash.substring(1);for(c=/([^&;=]+)=?([^&;]*)/g;d=c.exec(b);)a[decodeURIComponent(d[1])]=decodeURIComponent(d[2]);return a};b.prototype.Gc=function(){"pushState"in window.history?window.history.pushState("",
document.title,window.location.pathname):window.location.hash=""};b.prototype.Ab=function(){var a,b;a=window.location.search.indexOf("error=")!==-1?!0:!1;b=this.xc();this.Gc();if("access_token"in b)return this.S=b.access_token,console.log(""+this.a+": login() got access token: "+this.S),!0;else"client_id"in this.options?a===!0?console.log(""+this.a+": error authorizing client, not logging in"):(console.log("redirecting to auth_url = "+this.Yb),window.location=this.Yb):console.log("no client id, cant authenticate");
return!1};b.prototype.bb=function(a){var b;this.Jc=!0;this.fd=a;b=localStorage.getItem(""+this.namespace+"/username");if(b!=x&&b!==a)return console.log("user changed, clearing localStorage: "+a+" != stored:"+b),this.M=[],localStorage.clear(),localStorage.setItem(""+this.namespace+"/username",a)};b.prototype.Rc=function(a){return this.T=a};b.prototype.Sc=function(a){return this.vb=a};b.prototype.Pc=function(a){return this.Ta=a};b.prototype.Qc=function(a){return this.ua=a};b.prototype.get=function(a){return this.data.e!=
x&&this.data.e[a]!=x?this.f.q(this.data.e[a].object):x};b.prototype.xb=function(){var b,c,d,f,i;b={};d=0;if(this.data.e!=x)for(f in i=this.data.e,i)a.call(i,f)&&(c=i[f],c=c.last!=x?this.f.q(c.last):this.f.q(c.object),b[f]=c,d+=1);console.log(""+this.a+": get_all_data returned "+d);return b};b.prototype.Ua=function(){var b,c,d,f,i,j=this;console.log(""+this.a+": initialize_client called");if(this.T!=x&&this.data.e!=x){d=0;i=this.data.e;for(c in i)a.call(i,c)&&(b=i[c],d+=1);console.log(""+this.a+": checking notifies "+
d);i=this.data.e;for(c in i)a.call(i,c)&&(b=i[c],this.ic[c]===!0?d-=1:(b.last!=x&&this.f.I(b.last)>0?(console.log(""+this.a+": NOTIFY using s_data.last for "+c),console.log(b),b=this.f.q(b.last),this.h.m&&this.pa(c)):b=this.f.q(b.object),f=function(a,b){j.T(a,b,x);d-=1;if(d===0&&j.ua!=x)return j.ua()},setTimeout(function(a,b){return function(){return f(a,b)}}(c,b))));if(d===0&&this.ua!=x)return console.log(""+this.a+" no scheduled notifications, initializing"),this.ua()}};b.prototype.start=function(){var a,
b;console.log(""+this.a+": start()");if(!this.S||this.S==="none"||this.S==="None")console.log(""+this.a+": no auth token available, cannot start auth_token:"+this.S);else return this.options.host.indexOf("simperium.com")!==-1?(b=!0,a=443):(b=!1,a=this.options.port),a={port:a,Hb:b,Ba:!1,Eb:!0,Gb:"change:"+this.wa+":"+this.la+"/"+this.a+"/"+this.S,U:500,Za:["websocket","xhr-polling","xhr-multipart"]},"update_delay"in this.options||(this.options.update_delay=0),console.log(""+this.a+" connect to "+this.options.host+
" - socket.io opts:"),console.log(a),this.h=new Da.nc(this.options.host,a),this.h.ha("connect",this.ob),this.h.ha("message",this.rb),this.h.ha("reconnect",this.sb),this.h.ha("disconnect",this.qb),this.h.ha("connecting",this.pb),this.h.p()};b.prototype.Z=function(){console.log(""+this.a+": _refresh_store(): loading index: dataurl: "+this.ac);this.h.send("i")};b.prototype.Db=function(b){var c,d,f,i,j=this;console.log(""+this.a+": on_index(): index received, cv = "+b.cv);console.log(b);d=0;b.cv!=x?(this.data.t=
b.cv,this.Ub()):this.data.t=0;this.ga={};i=b.index;for(c in i)a.call(i,c)&&(f=i[c],this.ga[c]=!1,this.data.e[c]!=x&&this.data.e[c].version===f?this.ga[c]=!0:(d+=1,console.log(""+this.a+": retrieving "+c+"/"+f),this.h.send("e:"+c+"."+f)));f=this.data.e;for(c in f)a.call(f,c)&&b.index[c]==x&&(delete this.data.e[c],this.Pa(c),setTimeout(function(a){return function(){return j.T(a,x,x)}}(c)),console.log(""+this.a+" deleting "+c+" no longer in index"));console.log(""+this.a+": entries in loading_index = "+
this.f.I(this.ga)+", loading versions: "+d);if(this.f.I(this.ga)===0||d===0)return console.log(""+this.a+": nothing to load, index loaded"),this.Ja()};b.prototype.jc=function(){var a=this;console.log(""+this.a+": index doesnt exist or other error");if(!this.h.m)return setTimeout(function(){return a.h.p()})};b.prototype.zb=function(a,b){var c,d,f,j;if(!(a in this.data.e))return!1;c=Math.max(this.data.e[a].version-(b+1),1);j=[];d=c;for(f=this.data.e[a].version-1;c<=f?d<=f:d>=f;c<=f?d++:d--)console.log(""+
this.a+": loading version "+a+"."+d),j.push(this.h.send("e:"+a+"."+d));return j};b.prototype.ec=function(a,b){return this.h.send("e:"+(""+a+"."+b))};b.prototype.Va=function(b,c,d){var f;console.log(""+this.a+": on_entity_version("+b+", "+c+", "+d+")");f=x;b!=x&&(f=this.f.q(b));if(c in this.data.e&&d<this.data.e[c].version){if(this.vb)return this.vb(c,f,d)}else{this.data.e[c]={id:c,object:b,version:parseInt(d)};this.ba(c);this.options.stream_index===!0&&(this.T(c,f,d),this.ic[c]=!0);this.ga[c]=!0;
b=0;d=this.ga;for(c in d)a.call(d,c)&&this.ga[c]===!1&&b++;return b>0?console.log("loading left: "+b):this.Ja()}};b.prototype.Ja=function(){var a=this;console.log(""+this.a+": index loaded, initialized: "+this.za+", connected: "+this.h.m);this.za===!1&&this.Ua();this.za=!0;return this.h.m===!1?setTimeout(function(){return a.h.p()}):this.Ca()};b.prototype.pb=function(a){return console.log(""+this.a+": connecting: "+a)};b.prototype.sb=function(){return console.log(""+this.a+": reconnected")};b.prototype.ob=
function(){return console.log(""+this.a+": connected")};b.prototype.qb=function(){return console.log(""+this.a+": disconnected")};b.prototype.rb=function(b){var c,d,f,i=this;if(b.substr(0,5)==="auth:")if(b=b.substr(5),b.substr(0,7)==="expired")return console.log(""+this.a+": auth expired"),this.h.N();else if(this.bb(b),this.za){b=this.data.e;for(c in b)a.call(b,c)&&this.pa(c);setTimeout(function(){return i.ta()});return setTimeout(function(){return i.Ca()})}else setTimeout(function(){return i.Z()});
else if(b.substr(0,4)==="cv:?")return console.log(""+this.a+": cv out of sync, refreshing index"),setTimeout(function(){return i.Z()});else if(b.substr(0,2)==="c:"){c=JSON.parse(b.substr(2));if(this.data.t==="0"&&c.length===0&&!this.Lc)this.Lc=!0,this.Z();return this.Cb(c)}else if(b.substr(0,2)==="u:")return this.Jd=JSON.parse(b.substr(2)),this.data.t===0||this.data.t==="0"?setTimeout(function(){return i.Z()}):setTimeout(function(){return i.Ca()});else if(b.substr(0,2)==="i:")return console.log(""+
this.a+": index received"),this.Db(JSON.parse(b.substr(2)));else if(b.substr(0,2)==="e:")return f=b.indexOf("\n"),d=b.substr(2,f-2),c=d.substr(d.lastIndexOf(".")+1),d=d.substr(0,d.lastIndexOf(".")),b=b.substr(f+1),b==="?"?this.Va(x,d,c):(b=JSON.parse(b),this.Va(b.data,d,c))};b.prototype.Ma=function(b,a,c,d){var f,j,m,n,p;console.log(""+this.a+": _notify_client("+b+", "+a+", "+c+", "+JSON.stringify(d)+")");if(this.Ta){f=this.Ta(b);j=x;p=[];if(this.f.V(f)==="array"&&(m=f[2],n=f[1],f=f[0],j=this.Ia(m)))p[0]=
j.startOffset,"endOffset"in j&&(p[1]=j.endOffset);if(f!=x&&c!=x){f=this.f.Aa(c,f);this.f.I(f)===0?a=c:d=this.f.Da(f,d,c);if(j){a=this.f.ub(a,d,n,p);m!=x&&"value"in m&&(m.value=a[n]);j.startOffset=p[0];if(p.length>1)j.endOffset=p[1],j.startOffset>=j.endOffset&&(j.collapsed=!0);this.Qa(m,j)}else a=this.f.R(a,d);return this.T(b,a)}else return a?this.T(b,a):this.T(b,x)}};b.prototype.pa=function(b){var a,c,d,f,j;if(!(b in this.data.e))return!1;c=this.data.e[b];if(c.change){a=!1;j=this.M;d=0;for(f=j.length;d<
f;d++)b=j[d],b.id===c.change.id&&b.ccid===c.change.ccid&&(a=!0);return!a?(this.sa(c.change),!0):!1}if(c.check!=x)return!1;if(c.last!=x&&this.f.I(c.last)>0&&this.f.u(c.object,c.last))return c.last=x,this.ba(b),!1;c.change=this.La(b);this.sa(c.change);return!0};b.prototype.update=function(b,a){var c,d=this;if(b==x&&a==x)return!1;b==x&&(b=this.Y()+this.Y()+this.Y()+this.Y());b in this.data.e||(this.data.e[b]={id:b,object:{},version:x,change:x,check:x});c=this.data.e[b];c.last=this.f.q(a);c.modified=
this.Hc();this.ba(b);if(this.h.m&&c.change==x&&c.check==x)return c.check=setTimeout(function(b,a){return function(){a.check=x;a.change=d.La(b);a.last=x;d.ba(b);return d.sa(a.change)}}(b,c),this.options.update_delay)};b.prototype.La=function(b){var a,c,d,f,j;d=this.data.e[b];j=this.M;a=0;for(f=j.length;a<f;a++)if(c=j[a],String(b)===c.id)return console.log(""+this.a+": _make_change("+b+") found pending change, aborting"),x;c={id:String(b),ccid:String(this.data.va++)};if(this.za)a=this.Ta(b),this.f.V(a)===
"array"&&(a=a[0]);else if(d.last!=x)a=d.last;else return x;d.version!=x&&(c.sv=d.version);a===x&&d.version!=x?(c.o="-",console.log(""+this.a+": DELETION requested for "+b)):a!=x&&d.object!=x?(c.o="M",c.v=this.f.Aa(d.object,a),this.f.I(c.v)===0&&(c=x)):c=x;return c};b.prototype.sa=function(b){if(b!=x&&(this.M.push(b),this.h!=x&&this.h.m?this.h.send("c:"+JSON.stringify(b)):console.log(""+this.a+": in queue_change not sending yet"),this.Sa==x))return this.Sa=setTimeout(this.ta,1E4)};b.prototype.ta=function(){var b,
a,c,d;if(this.M.length===0)this.Sa=x;else if(this.h.m){d=this.M;a=0;for(c=d.length;a<c;a++)b=d[a],this.h.send("c:"+JSON.stringify(b));return this.Sa=setTimeout(this.ta,1E4)}else this.Sa=x};b.prototype.Ca=function(){console.log(""+this.a+": requesting changes since cv:"+this.data.t);this.h.send("cv:"+this.data.t)};b.prototype.Cb=function(b){var a,c,d,i,j,m,n,p,r,w,t,u,q,v=this;c=[];p=!1;console.log(""+this.a+": on_changes(): response=");console.log(b);r=0;for(w=b.length;r<w;r++){a=b[r];console.log(""+
this.a+": processing id="+a.id);d=[];u=this.M;i=0;for(t=u.length;i<t;i++)if(j=u[i],a.clientid===this.wa&&a.id===j.id&&("ccid"in a&&a.ccid===j.ccid||"ccids"in a&&(q=j.ccid,f.call(a.ccids,q)>=0)))a.local=!0,d.push(j),c.push(a.id);j=0;for(i=d.length;j<i;j++)n=d[j],this.data.e[n.id].change=x,this.M=function(){var a,b,c,d;c=this.M;d=[];a=0;for(b=c.length;a<b;a++)m=c[a],m!==n&&d.push(m);return d}.call(this);if("error"in a)a.error===409?console.log(""+this.a+": on_changes(): duplicate change, ignoring"):
(a.error===405?console.log(""+this.a+": on_changes(): bad version"):console.log(""+this.a+": error for last change, reloading"),a.id in this.data.e&&(this.data.e[a.id].version=x),p=!0);else if(j=a.o,d=a.id,j==="-"?(delete this.data.e[d],this.Pa(d),"local"in a||this.Ma(a.id,x,x,x)):j==="M"?(i=this.data.e[d],"sv"in a&&i!=x&&i.version!=x&&i.version===a.sv||!("sv"in a)?(i==x&&(this.data.e[d]={id:d,object:{},version:x,last:x,change:x,check:x},i=this.data.e[d]),j=this.f.q(i.object),i.object=this.f.R(i.object,
a.v),i.version=a.ev,i=this.f.q(i.object),this.ba(d),"local"in a||this.Ma(a.id,i,j,a.v)):i!=x&&i.version!=x&&a.ev<=i.version?console.log(""+this.a+": old or duplicate change received, ignoring, change.ev="+a.ev+", s_data.version:"+i.version):(i!=x?console.log(""+this.a+": version mismatch couldnt apply change, change.ev:"+a.ev+", s_data.version:"+i.version):console.log(""+this.a+": version mismatch couldnt apply change, change.ev:"+a.ev+", s_data null"),i!=x&&(this.data.e[d].version=x),p=!0)):console.log(""+
this.a+": no operation found for change"),!p)this.data.t=a.cv,this.Ub(),console.log(""+this.a+": checkpoint cv="+this.data.t)}if(p)console.log(""+this.a+": reload needed, refreshing store"),setTimeout(function(){return v.Z()});else{b=function(a){setTimeout(function(){return v.pa(a)},v.options.update_delay)};a=0;for(p=c.length;a<p;a++)d=c[a],b(d)}};b.prototype.Ia=A();b.prototype.Ia=function(a){if("activeElement"in a&&!a.activeElement)return x;var b=this.c.l/2,c=a.value,d={};if("selectionStart"in a){try{var f=
a.selectionStart,j=a.selectionEnd}catch(m){return x}d.ja=c.substring(f-b,f);d.mc=c.substring(f,f+b);d.startOffset=f;d.collapsed=f==j;if(!d.collapsed)d.ea=c.substring(j-b,j),d.cc=c.substring(j,j+b),d.endOffset=j}else{for(f=a;f.parentNode;)f=f.parentNode;if(!f.selection||!f.selection.createRange)return x;c=f.selection.createRange();if(c.parentElement()!=a)return x;f=f.body.createTextRange();d.collapsed=c.text=="";f.moveToElementText(a);if(!d.collapsed)f.setEndPoint("EndToEnd",c),d.ea=f.text,d.endOffset=
d.ea.length,d.ea=d.ea.substring(d.ea.length-b);f.setEndPoint("EndToStart",c);d.ja=f.text;d.startOffset=d.ja.length;d.ja=d.ja.substring(d.ja.length-b);f.moveToElementText(a);f.setEndPoint("StartToStart",c);d.mc=f.text.substring(0,b);if(!d.collapsed)f.setEndPoint("StartToEnd",c),d.cc=f.text.substring(0,b)}if("scrollTop"in a)d.scrollTop=a.scrollTop/a.scrollHeight,d.scrollLeft=a.scrollLeft/a.scrollWidth;return d};b.prototype.Qa=A();b.prototype.Qa=function(a,b){this.c.ab=1E3;this.c.Nb=0.9;var c=this.c.l/
2,d=a.value,f=b.ja+b.mc,j,m=R(this.c,d,f,b.startOffset-c);m!==x&&(j=d.substring(m,m+f.length),f=I(this.c,f,j,!1),m+=M(f,b.ja.length));var n=x;b.collapsed||(f=b.ea+b.cc,n=R(this.c,d,f,b.endOffset-c),n!==x&&(j=d.substring(n,n+f.length),f=I(this.c,f,j,!1),n+=M(f,b.ea.length)));if(m===x&&n!==x)m=n;else if(m===x&&n===x)m=b.startOffset;n===x&&(n=m);if("selectionStart"in a)a.selectionStart=m,a.selectionEnd=n;else{for(c=a;c.parentNode;)c=c.parentNode;if(!c.selection||!c.selection.createRange)return;d=a.value.substring(0,
m);d=d.replace(/\r\n/g,"\n").length;c=c.body.createTextRange();c.moveToElementText(a);c.collapse(!0);c.moveStart("character",d);if(!b.collapsed)d=a.value.substring(m,n),m=d.replace(/\r\n/g,"\n").length,c.moveEnd("character",m);c.select()}if("scrollTop"in b)a.scrollTop=b.scrollTop*a.scrollHeight,a.scrollLeft=b.scrollLeft*a.scrollWidth};return b}();window.Simperium=b;b.prototype.set_notify=b.prototype.Rc;b.prototype.set_notify_version=b.prototype.Sc;b.prototype.set_get_data=b.prototype.Pc;b.prototype.set_initialized=
b.prototype.Qc;b.prototype.get_all_data=b.prototype.xb;b.prototype.start=b.prototype.start;b.prototype.initialize_client=b.prototype.Ua;b.prototype.login=b.prototype.Ab;b.prototype.load_versions=b.prototype.zb}).call(this);
